=== communitiesuk/epb-view-model/api/schemas/xml/SAP-Schema-NI-14.2/Messages/ExternalDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="EPC" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="EPC" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
			This schema is used to provide 
				(a) the texts of recommendations on EPCs
				(b) addenda that may appear on RdSAP EPCs
				(c) the options for Related Party Disclosure
		</xs:documentation>
	</xs:annotation>
	<xs:element name="ExternalDefinitions" type="ExternalDefinitions"/>
	<xs:complexType name="ExternalDefinitions">
		<xs:sequence>
			<xs:element name="Revision-Number" type="xs:string">
				<xs:annotation>
					<xs:documentation>The version number of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Revision-Date" type="xs:date">
				<xs:annotation>
					<xs:documentation>The date of the latest revision to any of the texts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Country" type="Country" maxOccurs="3"/>
			<xs:element name="Addendum" type="Addendum" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Related-Party-Disclosure" type="Related-Party-Disclosure" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Country">
		<xs:sequence>
			<xs:element name="Country-Code" type="UKCountryCode"/>
			<xs:element name="Recommendation" type="Recommendation" maxOccurs="unbounded"/>
			<xs:element name="Footnote-Text" type="Sentence" minOccurs="0" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Recommendation">
		<xs:sequence>
			<xs:element name="Improvement-Number" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>Recommendations are selected by recommendation number according to the criteria in Appendix T of the SAP specification.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Summary" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>A short description of the improvement.  English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Heading" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Text to precede the improvement description. English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Improvement-Description" type="Sentence" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Detailed description of the improvement.  English only, or English and Welsh</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Has-Footnote" type="xs:boolean" default="false" minOccurs="0">
				<xs:annotation>
					<xs:documentation>If true the Footnote-Text appears at the bottom of the page.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Addendum">
		<xs:annotation>
			<xs:documentation>Addendum-Number is unique for the text concerned. If an addendum is deleted the number will not be re-used.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Addendum-Number" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>The text of an addendum is picked up via the Addendum-Number.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Circumstances" type="xs:string">
				<xs:annotation>
					<xs:documentation>The circumstances under which this addendum should be included.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Addendum-Text" type="Sentence" minOccurs="2" maxOccurs="2">
				<xs:annotation>
					<xs:documentation>Text to be included on the EPC (English and Welsh versions).</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Related-Party-Disclosure">
		<xs:annotation>
			<xs:documentation>List of possible texts for Related Party Disclosure on EPCs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Disclosure-Code" type="xs:positiveInteger"/>
			<xs:element name="Disclosure-Text" type="Sentence" minOccurs="2" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="LanguageCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>English</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Welsh</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UKCountryCode">
		<xs:annotation>
			<xs:documentation>Code which indicates the country within the UK, taken from BS 6879.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="EAW">
				<xs:annotation>
					<xs:documentation>England and Wales</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SCT">
				<xs:annotation>
					<xs:documentation>Scotland</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NIR">
				<xs:annotation>
					<xs:documentation>Northern Ireland</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Sentence" type="Sentence"/>
	<xs:complexType name="Sentence">
		<xs:annotation>
			<xs:documentation>String value with a language code for natural-language text.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="LanguageCode" use="required">
					<xs:annotation>
						<xs:documentation>Identifies the language that the sentence is recorded in.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== communitiesuk/epb-view-model/api/schemas/xml/SAP-Schema-15.0/Messages/ExternalDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--EPC Recommendations, RdSAP Addenda and Related Party Disclosure-->
<EPC:ExternalDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="EPC ExternalDefinitions.xsd" xmlns:EPC="EPC">
  <Revision-Number>3.0</Revision-Number>
  <Revision-Date>2011-03-01</Revision-Date>
  <Country>
    <Country-Code>EAW</Country-Code>
    <Recommendation>
      <Improvement-Number>1</Improvement-Number>
      <Improvement-Summary language="1">Insulate hot water cylinder with 80 mm jacket</Improvement-Summary>
      <Improvement-Summary language="2">Inswleiddio’r silindr dŵr poeth gyda siaced 80 mm</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Fitting an 80 mm cylinder jacket around hot water cylinder helps maintain water at required temperature, reducing energy usage and lowering fuel bills. </Improvement-Description>
      <Improvement-Description language="2">Mae gosod siaced silindr 80 mm o amgylch silindr dŵr poeth yn helpu i gynnal tymheredd y dŵr ble mae ei angen, gan leihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>2</Improvement-Number>
      <Improvement-Summary language="1">Increase hot water cylinder insulation</Improvement-Summary>
      <Improvement-Summary language="2">Cynyddu inswleiddiad dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Increasing thickness of existing insulation around hot water cylinder with additional cylinder jacket or other insulation will help maintain water at required temperature, reducing energy usage and lowering fuel bills.</Improvement-Description>
      <Improvement-Description language="2">Bydd cynyddu trwch yr inswleiddiad presennol o amgylch silindr dŵr poeth â siaced silindr ychwanegol neu inswleiddiad arall yn helpu i gynnal tymheredd y dŵr ble mae ei angen, gan leihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>3</Improvement-Number>
      <Improvement-Summary language="1">Add additional 80 mm jacket to hot water cylinder</Improvement-Summary>
      <Improvement-Summary language="2">Ychwanegu siaced 80 mm ychwanegol i’r siaced dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Hot water cylinder insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad silindr dŵr poeth</Improvement-Heading>
      <Improvement-Description language="1">Increasing thickness of existing insulation by adding 80 mm cylinder jacket will help maintain water at required temperature, reducing energy usage and lowering fuel bills.</Improvement-Description>
      <Improvement-Description language="2">Bydd cynyddu trwch yr inswleiddiad presennol drwy ychwanegu siaced silindr 80 mm yn helpu i gynnal tymheredd y dŵr ble mae ei angen, gan leihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>4</Improvement-Number>
      <Improvement-Summary language="1">Hot water cylinder thermostat</Improvement-Summary>
      <Improvement-Summary language="2">Thermostat silindr dŵr poeth</Improvement-Summary>
      <Improvement-Heading language="1">Cylinder thermostat</Improvement-Heading>
      <Improvement-Heading language="2">Thermostat silindr</Improvement-Heading>
      <Improvement-Description language="1">A hot water cylinder thermostat switches off the boiler when water reaches the required temperature, reducing energy usage and lowering fuel bills. Ask a plumber or heating engineer to install this.</Improvement-Description>
      <Improvement-Description language="2">Mae thermostat silindr dŵr poeth yn diffodd y bwyler pan fydd y dŵr yn cyrraedd y tymheredd y mae ei angen, gan leihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd. Gofynnwch i blymwr neu beiriannydd gwresogi ei osod.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>5</Improvement-Number>
      <Improvement-Summary language="1">Increase loft insulation to 270 mm</Improvement-Summary>
      <Improvement-Summary language="2">Cynyddu inswleiddiad croglofft i 270 mm</Improvement-Summary>
      <Improvement-Heading language="1">Loft insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddiad croglofft</Improvement-Heading>
      <Improvement-Description language="1">Loft insulation laid in the loft space or between roof rafters to a depth of at least 270 mm significantly reduces heat loss through the roof, improving levels of comfort, reducing energy use and lowering fuel bills. The loft space must have adequate ventilation to prevent dampness. Further information about loft insulation and details of local contractors can be obtained from the National Insulation Association (www.nationalinsulationassociation.org.uk).</Improvement-Description>
      <Improvement-Description language="2">Mae inswleiddiad yn y gofod yn y groglofft neu rhwng trawstiau’r to i ddyfnder o 270 mm o leiaf yn lleihau’n sylweddol ar golli gwres drwy’r to, gan wella lefelau cysur, lleihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd. Rhaid i’r gofod yn y groglofft gael ei awyru’n ddigonol i atal lleithder. Mae rhagor o wybodaeth am inswleiddio’r groglofft a manylion am gontractwyr lleol ar gael gan y Gymdeithas Inswleiddio Genedlaethol (www.nationalinsulationassociation.org.uk).</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>6</Improvement-Number>
      <Improvement-Summary language="1">Cavity wall insulation</Improvement-Summary>
      <Improvement-Summary language="2">Inswleiddio waliau ceudod</Improvement-Summary>
      <Improvement-Heading language="1">Cavity wall insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddio waliau ceudod</Improvement-Heading>
      <Improvement-Description language="1">Cavity wall insulation, to fill the gap between the inner and outer layers of external walls with an insulating material, reduces heat loss, improving levels of comfort, reducing energy use and lowering fuel bills. Further information about cavity wall insulation and details of local installers can be obtained from the National Insulation Association (www.nationalinsulationassociation.org.uk).</Improvement-Description>
      <Improvement-Description language="2">Mae inswleiddio waliau ceudod, i lenwi’r bwlch rhwng haen fewnol a haen allanol y waliau allanol â deunydd inswleiddio, yn lleihau’r gwres sy’n cael ei golli, gan wella lefelau cysur, lleihau’r ynni sy’n cael ei ddefnyddio a gostwng biliau tanwydd. Mae rhagor o wybodaeth am inswleiddio waliau ceudod a manylion am osodwyr lleol ar gael gan y Gymdeithas Inswleiddio Genedlaethol (www.nationalinsulationassociation.org.uk).</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>7</Improvement-Number>
      <Improvement-Summary language="1">50 mm internal or external wall insulation</Improvement-Summary>
      <Improvement-Summary language="2">Inswleiddio waliau mewnol neu allanol o 50 mm</Improvement-Summary>
      <Improvement-Heading language="1">Internal or external wall insulation</Improvement-Heading>
      <Improvement-Heading language="2">Inswleiddio waliau mewnol neu allanol</Improvement-Heading>
      <Improvement-Description language="1">Solid wall insulation involves adding a layer of insulation to either the inside or the outside surface of the external walls, which reduces heat loss and lowers fuel bills. Further information can be obtained from the National Insulation Association (www.nationalinsulationassociation.org.uk).</Improvement-Description>
      <Improvement-Description language="2">Mae inswleiddio waliau solet yn golygu ychwanegu haen inswleiddio nail ai y tu mewn neu y tu allan i’r waliau allanol, sy’n lleihau’r gwres ac yn gostwng biliau tanwydd. Mae rhagor o wybodaeth ar gael gan y Gymdeithas Inswleiddio Genedlaethol (www.nationalinsulationassociation.org.uk).</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>8</Improvement-Number>
      <Improvement-Summary language="1">Replace single glazed windows with low-E double glazing</Improvement-Summary>
      <Improvement-Summary language="2">Newid ffenestri gwydr sengl am rai gwydr dwbl E-isel</Improvement-Summary>
      <Improvement-Heading language="1">Double glazing</Improvement-Heading>
      <Improvement-Heading language="2">Gwydr dwbl</Improvement-Heading>
      <Improvement-Description language="1">Replacing single-glazed windows with double glazing will improve comfort in the home by reducing draughts and cold spots near windows. Building Regulations apply to this work.</Improvement-Description>
      <Improvement-Description language="2">Bydd gosod ffenestri gwydr dwbl yn lle ffenestri gwydr sengl yn gwella cysur yn y cartref drwy leihau drafftiau a mannau oer ger ffenestri. Mae’r Rheoliadau Adeiladu yn gymwys i’r gwaith hwn.</Improvement-Description>
    </Recommendation>
    <Recommendation>
      <Improvement-Number>9</Improvement-Number>
      <Improvement-Summary language="1">Secondary glazing to single glazed windows</Improvement-Summary>
      <Improvement-Summary language="2">Gwydriad eilaidd i ffenestri gwydr sengl</Improvement-Summary>
